/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Toshiba-PC
 */
public class AdmGerencia extends javax.swing.JFrame {

    /**
     * Creates new form AdmGerecia
     */
    public AdmGerencia() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar = new javax.swing.JButton();
        btnAdministrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGestinar = new javax.swing.JButton();
        btnAdministrar1 = new javax.swing.JButton();
        btnAdministrar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(255, 153, 204));
        btnActualizar.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnActualizar.setText("Productos");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, 90));

        btnAdministrar.setBackground(new java.awt.Color(255, 153, 204));
        btnAdministrar.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnAdministrar.setText("Salir");
        btnAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 130, 40));

        jLabel2.setFont(new java.awt.Font("Savoye LET", 0, 48)); // NOI18N
        jLabel2.setText("Administracion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btnGestinar.setBackground(new java.awt.Color(255, 153, 204));
        btnGestinar.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnGestinar.setText("Gestion De Ventas");
        btnGestinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestinarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 190, 90));

        btnAdministrar1.setBackground(new java.awt.Color(255, 153, 204));
        btnAdministrar1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnAdministrar1.setText("Usuarios");
        btnAdministrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 190, 90));

        btnAdministrar2.setBackground(new java.awt.Color(255, 153, 204));
        btnAdministrar2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnAdministrar2.setText("Proovedores");
        btnAdministrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 190, 90));

        jLabel3.setFont(new java.awt.Font("Bodoni Ornaments", 0, 48)); // NOI18N
        jLabel3.setText("Administrasdas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 650, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/morado.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestinarActionPerformed
        Principal p=new Principal();
        p.setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_btnGestinarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ActualizarCat c=new ActualizarCat();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarActionPerformed
        InicioSeccion i=new InicioSeccion();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdministrarActionPerformed

    private void btnAdministrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrar1ActionPerformed
        AdmUser a=new AdmUser();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdministrar1ActionPerformed

    private void btnAdministrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmGerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAdministrar;
    private javax.swing.JButton btnAdministrar1;
    private javax.swing.JButton btnAdministrar2;
    private javax.swing.JButton btnGestinar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
