
import java.awt.Toolkit;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Toshiba-PC
 */
public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        this.setLocation(-10,0);
        this.setSize(1383,735);
        PanelClientes.setVisible(true);
        PanelPedidos.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);
        btnAgregar.setVisible(true);
        btnAutorizar.setVisible(false);
        btnAgregarPedido.setVisible(false);
        btnCredito.setVisible(false);
        btnAbonar.setVisible(false);
        jPanelBotonC.setBackground(new java.awt.Color(200,200,200));
        JTitulo.setText("Clientes");
        Date fecha=new Date();
        jFecha.setDate(fecha);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCAbonos = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblAbonos1 = new javax.swing.JTable();
        PanelCatalago = new javax.swing.JPanel();
        PanelCatalago1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        PanelCatalago2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        PanelCatalago3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        PanelTitulo = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTitulo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PanelPedidos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaP = new javax.swing.JTable();
        PanelClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaC = new javax.swing.JTable();
        jPanelConAbonos = new javax.swing.JPanel();
        btnConsultarAbonos = new javax.swing.JButton();
        jPanelAbonos = new javax.swing.JPanel();
        btnAbonos = new javax.swing.JButton();
        PanelAbonos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAbonos = new javax.swing.JTable();
        PanelEstatus = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEstatus = new javax.swing.JTable();
        jPanelBotonP = new javax.swing.JPanel();
        btnConPedidos = new javax.swing.JButton();
        jPanelBotonCE = new javax.swing.JPanel();
        btnConEstatis = new javax.swing.JButton();
        jPanelBotonC = new javax.swing.JPanel();
        btnConCliente = new javax.swing.JButton();
        jPanelE = new javax.swing.JPanel();
        btnCatalagos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAbonar = new javax.swing.JButton();
        btnCredito = new javax.swing.JButton();
        btnAgregarPedido = new javax.swing.JToggleButton();
        btnAgregar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblRestante = new javax.swing.JLabel();
        btnAutorizar = new javax.swing.JButton();
        PanelRegistro = new javax.swing.JPanel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtPedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbCalzado = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        sTalla = new javax.swing.JSpinner();
        jFecha = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblAbonos = new javax.swing.JLabel();
        txtCatalogo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Libro1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCatalago = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAbonos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Id Pedido", "Nombre", "Apellido Paterno", "Apellodo Materno", "Total abonos", "Credito", "Fecha", "Hora"
            }
        ));
        tblAbonos1.setRowHeight(25);
        tblAbonos1.setSelectionForeground(new java.awt.Color(204, 255, 255));
        jScrollPane6.setViewportView(tblAbonos1);

        javax.swing.GroupLayout PanelCAbonosLayout = new javax.swing.GroupLayout(PanelCAbonos);
        PanelCAbonos.setLayout(PanelCAbonosLayout);
        PanelCAbonosLayout.setHorizontalGroup(
            PanelCAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(PanelCAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE))
        );
        PanelCAbonosLayout.setVerticalGroup(
            PanelCAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(PanelCAbonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );

        getContentPane().add(PanelCAbonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 960, 470));

        PanelCatalago.setBackground(new java.awt.Color(255, 255, 255));

        PanelCatalago1.setBackground(new java.awt.Color(255, 255, 255));
        PanelCatalago1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCatalago1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelCatalago1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelCatalago1MouseExited(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CALZADO CONFORT.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelCatalago1Layout = new javax.swing.GroupLayout(PanelCatalago1);
        PanelCatalago1.setLayout(PanelCatalago1Layout);
        PanelCatalago1Layout.setHorizontalGroup(
            PanelCatalago1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalago1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        PanelCatalago1Layout.setVerticalGroup(
            PanelCatalago1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCatalago1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(24, 24, 24))
        );

        PanelCatalago2.setBackground(new java.awt.Color(255, 255, 255));
        PanelCatalago2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelCatalago2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelCatalago2MouseExited(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/andrea-calzado-min.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelCatalago2Layout = new javax.swing.GroupLayout(PanelCatalago2);
        PanelCatalago2.setLayout(PanelCatalago2Layout);
        PanelCatalago2Layout.setHorizontalGroup(
            PanelCatalago2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalago2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelCatalago2Layout.setVerticalGroup(
            PanelCatalago2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalago2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCatalago3.setBackground(new java.awt.Color(255, 255, 255));
        PanelCatalago3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelCatalago3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelCatalago3MouseExited(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/andrea-familia-min.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelCatalago3Layout = new javax.swing.GroupLayout(PanelCatalago3);
        PanelCatalago3.setLayout(PanelCatalago3Layout);
        PanelCatalago3Layout.setHorizontalGroup(
            PanelCatalago3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalago3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCatalago3Layout.setVerticalGroup(
            PanelCatalago3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCatalago3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout PanelCatalagoLayout = new javax.swing.GroupLayout(PanelCatalago);
        PanelCatalago.setLayout(PanelCatalagoLayout);
        PanelCatalagoLayout.setHorizontalGroup(
            PanelCatalagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCatalago1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCatalago2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCatalago3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCatalagoLayout.setVerticalGroup(
            PanelCatalagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalagoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PanelCatalagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelCatalago3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCatalagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelCatalago2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelCatalago1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(PanelCatalago, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 960, 470));

        PanelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 0, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Cerrar seccion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelTitulo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 120, 40));

        jLabel8.setFont(new java.awt.Font("Pristina", 0, 24)); // NOI18N
        jLabel8.setText("Angelina");
        PanelTitulo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 255));
        jLabel9.setText("Zapateria");
        PanelTitulo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JTitulo.setFont(new java.awt.Font("Freestyle Script", 1, 48)); // NOI18N
        JTitulo.setText("Clientes");
        PanelTitulo.add(JTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/morado.jpg"))); // NOI18N
        PanelTitulo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 110));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/morado.jpg"))); // NOI18N
        PanelTitulo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 0, 10, 110));

        getContentPane().add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 110));

        PanelPedidos.setLayout(new java.awt.BorderLayout());

        tblTablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pedido", "Id Cliente", "Nombre", "Apellido Paterno", "Apellido Materno", "Tipo de Calzado", "Color", "Talla", "Fecha", "Hora", "Descripcion", "Precio", "Id Calzado"
            }
        ));
        tblTablaP.setRowHeight(25);
        tblTablaP.setSelectionForeground(new java.awt.Color(204, 255, 255));
        tblTablaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTablaP);

        PanelPedidos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 960, 470));

        PanelClientes.setLayout(new java.awt.BorderLayout());

        tblTablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "Abdul", "Chalita", "Luna", "311239382", "07/12/1999", null, null}
            },
            new String [] {
                "Id Cliente", "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono", "Fecha Nacimiento", "Codigo postal", "Calle"
            }
        ));
        tblTablaC.setRowHeight(25);
        tblTablaC.setSelectionForeground(new java.awt.Color(204, 255, 255));
        tblTablaC.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tblTablaCHierarchyChanged(evt);
            }
        });
        tblTablaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTablaC);

        PanelClientes.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 960, 470));

        jPanelConAbonos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelConAbonos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelConAbonos.setLayout(new java.awt.BorderLayout());

        btnConsultarAbonos.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        btnConsultarAbonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConsultarAbono.png"))); // NOI18N
        btnConsultarAbonos.setText("Consultar creditos ");
        btnConsultarAbonos.setContentAreaFilled(false);
        btnConsultarAbonos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarAbonos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultarAbonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarAbonosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarAbonosMouseExited(evt);
            }
        });
        btnConsultarAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAbonosActionPerformed(evt);
            }
        });
        jPanelConAbonos.add(btnConsultarAbonos, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelConAbonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 130, 70));

        jPanelAbonos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelAbonos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAbonos.setLayout(new java.awt.BorderLayout());

        btnAbonos.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        btnAbonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abono1.png"))); // NOI18N
        btnAbonos.setText("Abonar");
        btnAbonos.setContentAreaFilled(false);
        btnAbonos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbonos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbonosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbonosMouseExited(evt);
            }
        });
        btnAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonosActionPerformed(evt);
            }
        });
        jPanelAbonos.add(btnAbonos, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelAbonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 130, 70));

        PanelAbonos.setLayout(new java.awt.BorderLayout());

        tblAbonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Id Pedido", "Nombre", "Apellido Paterno", "Apellodo Materno", "Cantidad abonada", "Fecha", "Hora"
            }
        ));
        tblAbonos.setRowHeight(25);
        tblAbonos.setSelectionForeground(new java.awt.Color(204, 255, 255));
        jScrollPane3.setViewportView(tblAbonos);

        PanelAbonos.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelAbonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 960, 470));

        PanelEstatus.setLayout(new java.awt.BorderLayout());

        tblEstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12321", "10", "German", "Orozco ", "Zuñiga", "Debe"},
                {"3123", "11", "Marlen", "Hernandez", "Gutierres", "Debe"},
                {"3213", "12", "Abdul", "Chalita", "Luna", "Pagado"}
            },
            new String [] {
                "Id Pedido", "Id CLiente", "Nombre", "Apellido Paterno", "Apellido Materno", "Estatus"
            }
        ));
        tblEstatus.setRowHeight(25);
        tblEstatus.setSelectionForeground(new java.awt.Color(204, 255, 255));
        tblEstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstatusMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblEstatus);

        PanelEstatus.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 960, 470));

        jPanelBotonP.setBackground(new java.awt.Color(204, 204, 255));
        jPanelBotonP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBotonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBotonPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBotonPMouseExited(evt);
            }
        });
        jPanelBotonP.setLayout(new java.awt.BorderLayout());

        btnConPedidos.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        btnConPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huarache.png"))); // NOI18N
        btnConPedidos.setText("Consultar Pedidos");
        btnConPedidos.setContentAreaFilled(false);
        btnConPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConPedidosMouseExited(evt);
            }
        });
        btnConPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConPedidosActionPerformed(evt);
            }
        });
        jPanelBotonP.add(btnConPedidos, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelBotonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 70));

        jPanelBotonCE.setBackground(new java.awt.Color(204, 204, 255));
        jPanelBotonCE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBotonCE.setLayout(new java.awt.BorderLayout());

        btnConEstatis.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        btnConEstatis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarEstatus.png"))); // NOI18N
        btnConEstatis.setText("Consultar Estatus");
        btnConEstatis.setContentAreaFilled(false);
        btnConEstatis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConEstatis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConEstatis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConEstatisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConEstatisMouseExited(evt);
            }
        });
        btnConEstatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConEstatisActionPerformed(evt);
            }
        });
        jPanelBotonCE.add(btnConEstatis, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelBotonCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 70));

        jPanelBotonC.setBackground(new java.awt.Color(204, 204, 255));
        jPanelBotonC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBotonC.setLayout(new java.awt.BorderLayout());

        btnConCliente.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        btnConCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clienta.png"))); // NOI18N
        btnConCliente.setText("Consultar Clientes");
        btnConCliente.setContentAreaFilled(false);
        btnConCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConClienteMouseExited(evt);
            }
        });
        btnConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConClienteActionPerformed(evt);
            }
        });
        jPanelBotonC.add(btnConCliente, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelBotonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 140, 70));

        jPanelE.setBackground(new java.awt.Color(204, 204, 255));
        jPanelE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelE.setLayout(new java.awt.BorderLayout());

        btnCatalagos.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        btnCatalagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estatus.png"))); // NOI18N
        btnCatalagos.setText("Catalagos");
        btnCatalagos.setContentAreaFilled(false);
        btnCatalagos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCatalagos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCatalagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCatalagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCatalagosMouseExited(evt);
            }
        });
        btnCatalagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalagosActionPerformed(evt);
            }
        });
        jPanelE.add(btnCatalagos, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbonar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAbonar.setText("Abonar");
        btnAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAbonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 180, 80));

        btnCredito.setText("Agregar credito");
        btnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoActionPerformed(evt);
            }
        });
        jPanel3.add(btnCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 180, 80));

        btnAgregarPedido.setText("Agregar pedido");
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 180, 80));

        btnAgregar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar cliente");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 180, 81));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel11.setText("Restante:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, -1, -1));

        lblRestante.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        jPanel3.add(lblRestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 27, 110, 60));

        btnAutorizar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAutorizar.setText("Autorizar pedido");
        btnAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAutorizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 186, 81));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 960, 150));

        PanelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        PanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellidoM.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        PanelRegistro.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 101, -1));

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel1.setText("Codigo Cliente");
        PanelRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel6.setText("Calle");
        PanelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        txtApellidoP.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        PanelRegistro.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 101, -1));

        txtCalle.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        PanelRegistro.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 160, -1));

        txtPedido.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        txtPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPedidoActionPerformed(evt);
            }
        });
        txtPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPedidoKeyTyped(evt);
            }
        });
        PanelRegistro.add(txtPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 74, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno");
        PanelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        txtCodigoP.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        PanelRegistro.add(txtCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 100, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno");
        PanelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel5.setText("Talla");
        PanelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        txtCliente.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });
        PanelRegistro.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 74, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel7.setText("Codigo postal");
        PanelRegistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel10.setText("Fechas");
        PanelRegistro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 50, -1));

        cmbCalzado.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cmbCalzado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bota", "Bota vaquera", "Calzado de protección", "Chancla", "Huarache", "Mocasín", "Pantufla", "Sandalia", "Calzado deportivo", "Zapato", "Zapatilla de plataforma", "Zapatilla de tacón" }));
        PanelRegistro.add(cmbCalzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 120, -1));

        txtTelefono.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        PanelRegistro.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 101, -1));

        jLabel18.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel18.setText("Telefono");
        PanelRegistro.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        txtNombre.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        PanelRegistro.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 101, -1));

        jLabel19.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel19.setText("Nombre");
        PanelRegistro.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel21.setText("Codigo del Pedido");
        PanelRegistro.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        cmbColor.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Azul", "Marrón", "Gris", "Verde", "Naranja", "Rosa", "Púrpura", "Rojo", "Blanco", "Amarillo" }));
        PanelRegistro.add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel22.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel22.setText("Color");
        PanelRegistro.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        sTalla.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        sTalla.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(20.5f), Float.valueOf(1.0f), Float.valueOf(40.0f), Float.valueOf(0.5f)));
        PanelRegistro.add(sTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 70, -1));
        PanelRegistro.add(jFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        jLabel23.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel23.setText("Tipo de Calzado");
        PanelRegistro.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel29.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel29.setText("Precio:");
        PanelRegistro.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        PanelRegistro.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 130, 60));

        jLabel30.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel30.setText("Abonos:");
        PanelRegistro.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        lblAbonos.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        PanelRegistro.add(lblAbonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 110, 60));

        txtCatalogo.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        txtCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatalogoActionPerformed(evt);
            }
        });
        txtCatalogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCatalogoKeyTyped(evt);
            }
        });
        PanelRegistro.add(txtCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 74, -1));

        jLabel24.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel24.setText("Codigo del Catalogo");
        PanelRegistro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        getContentPane().add(PanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 410, 470));

        Libro1.setBackground(new java.awt.Color(255, 255, 255));

        tblCatalago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"312", "Zapato", "Negrp", "28", null}
            },
            new String [] {
                "Codigo", "Tipo", "Color", "Talla", "Precio"
            }
        ));
        tblCatalago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCatalagoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblCatalago);

        javax.swing.GroupLayout Libro1Layout = new javax.swing.GroupLayout(Libro1);
        Libro1.setLayout(Libro1Layout);
        Libro1Layout.setHorizontalGroup(
            Libro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        Libro1Layout.setVerticalGroup(
            Libro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        getContentPane().add(Libro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 960, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelCatalago1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCatalago1MouseClicked
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(true);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        btnAgregarPedido.setVisible(false);
        btnCredito.setVisible(false);
        btnAutorizar.setVisible(false);
        btnAbonar.setVisible(false);
    }//GEN-LAST:event_PanelCatalago1MouseClicked

    private void PanelCatalago1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCatalago1MouseEntered
        PanelCatalago1.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_PanelCatalago1MouseEntered

    private void PanelCatalago1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCatalago1MouseExited
        PanelCatalago1.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_PanelCatalago1MouseExited

    private void PanelCatalago2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCatalago2MouseEntered
        PanelCatalago2.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_PanelCatalago2MouseEntered

    private void PanelCatalago2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCatalago2MouseExited
        PanelCatalago2.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_PanelCatalago2MouseExited

    private void PanelCatalago3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCatalago3MouseEntered
        PanelCatalago3.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_PanelCatalago3MouseEntered

    private void PanelCatalago3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCatalago3MouseExited
        PanelCatalago3.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_PanelCatalago3MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InicioSeccion i=new InicioSeccion();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblTablaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaPMouseClicked

    }//GEN-LAST:event_tblTablaPMouseClicked

    private void tblTablaCHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tblTablaCHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTablaCHierarchyChanged

    private void tblTablaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaCMouseClicked
        int seleccionar=tblTablaC.rowAtPoint(evt.getPoint());
        txtCliente.setText(String.valueOf(tblTablaC.getValueAt(seleccionar,0)));
        txtNombre.setText(String.valueOf(tblTablaC.getValueAt(seleccionar,1)));
        txtApellidoP.setText(String.valueOf(tblTablaC.getValueAt(seleccionar,2)));
        txtApellidoM.setText(String.valueOf(tblTablaC.getValueAt(seleccionar,3)));
        txtTelefono.setText(String.valueOf(tblTablaC.getValueAt(seleccionar,4)));
        //jFecha.setDate((tblTablaC.getValueAt(seleccionar,5)));
        txtCodigoP.setText(String.valueOf(tblTablaC.getValueAt(seleccionar,6)));

        PanelEstatus.setVisible(true);
        PanelAbonos.setVisible(false);
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        btnAutorizar.setVisible(true);
        btnCredito.setVisible(false);
        btnAbonar.setVisible(false);
        jPanelBotonCE.setBackground(new java.awt.Color(200,200,200));
        jPanelBotonC.setBackground(new java.awt.Color(204,204,255));
                JTitulo.setText("Estatus");

    }//GEN-LAST:event_tblTablaCMouseClicked

    private void btnConsultarAbonosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarAbonosMouseEntered
        jPanelConAbonos.setBackground(new java.awt.Color(200,200,200));
    }//GEN-LAST:event_btnConsultarAbonosMouseEntered

    private void btnConsultarAbonosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarAbonosMouseExited
        jPanelConAbonos.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnConsultarAbonosMouseExited

    private void btnConsultarAbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAbonosActionPerformed
        PanelAbonos.setVisible(true);
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        btnAgregarPedido.setVisible(false);
        //btnAgregar.setText("Agregar pago");
        btnCredito.setVisible(true);
        btnAutorizar.setVisible(false);
        btnAbonar.setVisible(false);
    }//GEN-LAST:event_btnConsultarAbonosActionPerformed

    private void btnAbonosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbonosMouseEntered
        jPanelAbonos.setBackground(new java.awt.Color(200,200,200));
    }//GEN-LAST:event_btnAbonosMouseEntered

    private void btnAbonosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbonosMouseExited
        jPanelAbonos.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnAbonosMouseExited

    private void btnAbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonosActionPerformed
        Abonar a=new Abonar();
        a.setVisible(true);
    }//GEN-LAST:event_btnAbonosActionPerformed

    private void tblEstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstatusMouseClicked

    }//GEN-LAST:event_tblEstatusMouseClicked

    private void btnConPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConPedidosMouseEntered
        jPanelBotonP.setBackground(new java.awt.Color(200,200,200));
    }//GEN-LAST:event_btnConPedidosMouseEntered

    private void btnConPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConPedidosMouseExited
        jPanelBotonP.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnConPedidosMouseExited

    private void btnConPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConPedidosActionPerformed
        PanelPedidos.setVisible(true);
        PanelClientes.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregarPedido.setVisible(true);
        //btnAgregar.setText("Agregar pedido");
        btnAgregar.setVisible(false);
        btnAutorizar.setVisible(false);
        btnCredito.setVisible(false);
        btnAbonar.setVisible(false);
    }//GEN-LAST:event_btnConPedidosActionPerformed

    private void jPanelBotonPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBotonPMouseEntered

    }//GEN-LAST:event_jPanelBotonPMouseEntered

    private void jPanelBotonPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBotonPMouseExited

    }//GEN-LAST:event_jPanelBotonPMouseExited

    private void btnConEstatisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConEstatisMouseEntered
        jPanelBotonCE.setBackground(new java.awt.Color(200,200,200));
    }//GEN-LAST:event_btnConEstatisMouseEntered

    private void btnConEstatisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConEstatisMouseExited
        jPanelBotonCE.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnConEstatisMouseExited

    private void btnConEstatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConEstatisActionPerformed
        PanelEstatus.setVisible(true);
        PanelAbonos.setVisible(false);
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        btnAutorizar.setVisible(true);
        btnCredito.setVisible(false);
        btnAbonar.setVisible(false);
    }//GEN-LAST:event_btnConEstatisActionPerformed

    private void btnConClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConClienteMouseEntered
        jPanelBotonC.setBackground(new java.awt.Color(200,200,200));
    }//GEN-LAST:event_btnConClienteMouseEntered

    private void btnConClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConClienteMouseExited
        jPanelBotonC.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnConClienteMouseExited

    private void btnConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConClienteActionPerformed
        PanelClientes.setVisible(true);
        PanelPedidos.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(true);
        btnAgregar.setText("Agregar cliente");
        btnAgregarPedido.setVisible(false);
        btnAutorizar.setVisible(false);
        btnCredito.setVisible(false);
        btnAbonar.setVisible(false);
    }//GEN-LAST:event_btnConClienteActionPerformed

    private void btnCatalagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatalagosMouseEntered
        jPanelE.setBackground(new java.awt.Color(200,200,200));
    }//GEN-LAST:event_btnCatalagosMouseEntered

    private void btnCatalagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatalagosMouseExited
        jPanelE.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnCatalagosMouseExited

    private void btnCatalagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalagosActionPerformed
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(true);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        btnAutorizar.setVisible(false);
        btnAgregarPedido.setVisible(false);
        btnCredito.setVisible(false);
        btnAbonar.setVisible(false);
    }//GEN-LAST:event_btnCatalagosActionPerformed

    private void btnAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarActionPerformed
        Abonar a=new Abonar();
        a.setVisible(true);
    }//GEN-LAST:event_btnAbonarActionPerformed

    private void btnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoActionPerformed
        Credito a=new Credito();
        a.setVisible(true);

        PanelEstatus.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(true);

        btnAgregar.setVisible(false);
        btnAgregarPedido.setVisible(false);
        btnCredito.setVisible(false);
        btnAutorizar.setVisible(false);
        btnAbonar.setVisible(true);
        
        jPanelAbonos.setBackground(new java.awt.Color(200,200,200));
        jPanelConAbonos.setBackground(new java.awt.Color(204,204,255));
                JTitulo.setText("Pagos");

    }//GEN-LAST:event_btnCreditoActionPerformed

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        PanelAbonos.setVisible(true);
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        //btnAgregar.setText("Agregar pago");
        btnAutorizar.setVisible(false);
        btnAgregarPedido.setVisible(false);
        btnCredito.setVisible(true);
        btnAbonar.setVisible(false);
        
        jPanelConAbonos.setBackground(new java.awt.Color(200,200,200));
        jPanelBotonP.setBackground(new java.awt.Color(204,204,255));
                JTitulo.setText("Creditos");

    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        PanelEstatus.setVisible(true);
        PanelAbonos.setVisible(false);
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        btnAutorizar.setVisible(true);
        btnCredito.setVisible(false);
        btnAgregarPedido.setVisible(false);
        btnAbonar.setVisible(false);
        
        jPanelBotonCE.setBackground(new java.awt.Color(200,200,200));
        jPanelBotonC.setBackground(new java.awt.Color(204,204,255));
                JTitulo.setText("Estatus");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizarActionPerformed
        PanelPedidos.setVisible(false);
        PanelClientes.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(true);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregar.setVisible(false);
        btnAgregarPedido.setVisible(false);
        btnCredito.setVisible(false);
        btnAutorizar.setVisible(false);
        btnAbonar.setVisible(false);
        
        jPanelE.setBackground(new java.awt.Color(200,200,200));
        jPanelBotonCE.setBackground(new java.awt.Color(204,204,255));
                JTitulo.setText("Catalagos");

    }//GEN-LAST:event_btnAutorizarActionPerformed

    private void txtPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPedidoActionPerformed

    private void txtPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPedidoKeyTyped

    }//GEN-LAST:event_txtPedidoKeyTyped

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped

    }//GEN-LAST:event_txtClienteKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped

    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

    }//GEN-LAST:event_txtNombreKeyTyped

    private void tblCatalagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCatalagoMouseClicked
        int seleccionar=tblCatalago.rowAtPoint(evt.getPoint());
        txtPedido.setText(String.valueOf(tblTablaC.getValueAt(seleccionar,0)));
        cmbCalzado.setSelectedIndex(1);
        cmbColor.setSelectedItem(1);

        PanelPedidos.setVisible(true);
        PanelClientes.setVisible(false);
        PanelAbonos.setVisible(false);
        PanelEstatus.setVisible(false);
        PanelCatalago.setVisible(false);
        Libro1.setVisible(false);
        PanelCAbonos.setVisible(false);

        btnAgregarPedido.setVisible(true);
        //btnAgregar.setText("Agregar pedido");
        btnAutorizar.setVisible(false);
        btnCredito.setVisible(false);
        btnAbonar.setVisible(false);
        
        jPanelBotonP.setBackground(new java.awt.Color(200,200,200));
        jPanelE.setBackground(new java.awt.Color(204,204,255));
                JTitulo.setText("Pedidos");

    }//GEN-LAST:event_tblCatalagoMouseClicked

    private void txtCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatalogoActionPerformed

    private void txtCatalogoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCatalogoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatalogoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTitulo;
    private javax.swing.JPanel Libro1;
    private javax.swing.JPanel PanelAbonos;
    private javax.swing.JPanel PanelCAbonos;
    private javax.swing.JPanel PanelCatalago;
    private javax.swing.JPanel PanelCatalago1;
    private javax.swing.JPanel PanelCatalago2;
    private javax.swing.JPanel PanelCatalago3;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelEstatus;
    private javax.swing.JPanel PanelPedidos;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JButton btnAbonar;
    private javax.swing.JButton btnAbonos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JToggleButton btnAgregarPedido;
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JButton btnCatalagos;
    private javax.swing.JButton btnConCliente;
    private javax.swing.JButton btnConEstatis;
    private javax.swing.JButton btnConPedidos;
    private javax.swing.JButton btnConsultarAbonos;
    private javax.swing.JButton btnCredito;
    private javax.swing.JComboBox<String> cmbCalzado;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAbonos;
    private javax.swing.JPanel jPanelBotonC;
    private javax.swing.JPanel jPanelBotonCE;
    private javax.swing.JPanel jPanelBotonP;
    private javax.swing.JPanel jPanelConAbonos;
    private javax.swing.JPanel jPanelE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAbonos;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblRestante;
    private javax.swing.JSpinner sTalla;
    private javax.swing.JTable tblAbonos;
    private javax.swing.JTable tblAbonos1;
    private javax.swing.JTable tblCatalago;
    private javax.swing.JTable tblEstatus;
    private javax.swing.JTable tblTablaC;
    private javax.swing.JTable tblTablaP;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCatalogo;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
